language: java
jdk:
  - openjdk8
sudo: false
env:
  global:
    - secure: WFA6nrIUvC4b98aHyjhiGsywLII3x+pIK6NXDnKCWyQ2ZLPn9/UOBu9FeFFvhEx/EU5rw2GHMcBbvbu6Zv1aOLAR85ZG9QbTCZIBbqWwJunDr6+eFL2teTOU7Ca+mZwqoiEUCG2Gjk3hQQ54VBiruGDmyEXD2YlZOrhewu6Y76pBroc9+z8irtgbm2sV6fAKB4tLMe5KBUY48bcEWu5JA+4qvpeieJIIjRO+uobXmdUlMJZvzzR7MVnclkMwfPfFSRTET6DSAZgTPLxAkxQIBvX2DFkqWv9DYbPGVXBAiMxuF1qUgLyy9FX9tNXvcGOVgYtM5rksaqfB8Gl2mRaFwjxiIR3a8jKpQoJ19uwfiQ6Xc+KFz4Eok7qlbJhzkDFZMlj9na3huy8leYY2KBHoWErqm94g3IYofwE2+50FvK/AZbaTyGRILmaE655vX/6bzAGJ0PmiDe4LD6yyTjmA8rQfF1mYBilwBt6tUDaR7kNPaVCxc9aGyF/xqeEqmNmcG/7aTYESOp1DOp1WwBRfg/J3qbDHoZDB1tLpm91CRix//TJocEg932Z9jyINtNfcKyzFB7MTQ5xclCclHoQvS7xnhd/mSPB/9lDI/iOdTJQD2vbItuexQy7XxmWwYvIfWngSDllU6j2JCP0RKQqYhgEsMF7sSC2ZL6JYIaIQHTg=
    - secure: VsMNVgxUak8e9gUVTESCZm317qrU++EtsRz2fvuFh4mbSfjjyoxPjVwL/DU7QloTT2DRyB3Pn0fXKMKOIV2NtZ2cq2X3qFJWSL3HVMAYKjYIvy9PxbiJBioEGqYXGJPgmtjIT0Ng89GuzpkHDAXeC/0QYZzXvd4Jn9TvsI7E8SZUMACCGi5GC8wRNrZq/cZGErg7eadPfsep2xgxwQFpidJW3y/MFUWuPFa7br/BzaR1LLRdOoPUBvJJbbJfuz2C8rLN00GT/fNdMWt706MIJJhv2UEsxGbCnnCWLEQxn74nq0gYVxTKW6yseHN2nMtrZYLHtJNCbHQdbEqqliqaxtWukW5FFnzJd4SVyYowjSyv+FscjpwSFu1WBANH09wBrcFwz9McM/wVBdtMwPdymtfrNhZ7bCgFY3vJ+jjw4IXpn6NPm5Hy3YQqLhFMjUU8WFSaQQGB9wG9DCB0U1dHf6G/IxVPJGzXxFJ+fOKlUooXAptB9MJ7I24AquOQ9GSEpr/a3oPD/OH3XdCbISIOCMz4OxPZNcnGftN+ZQXL+2/jNBei92pHkG75ENedYwQ/RhanlHm9WTvp+oxUqZuWmV5jYOcPxcLUj54k5ZSbqhn5q4vjwYVPyng6fthKzuR0xQ8jkWF4KJzpFVpK0avLlwmAGbNq080qbIF2XmMEry4=
before_install:
  - openssl aes-256-cbc -K $encrypted_90f62b3c4a37_key -iv $encrypted_90f62b3c4a37_iv -in private.key.enc -out private.key -d
  - chmod +x travis.sh
  - pip install --user codecov
install: true
after_success:
- codecov
script:
- "./travis.sh"
