language: java
sudo: false
before_install:
  - pip install --user codecov
install: true
after_success:
  - codecov
script:
  - mvn test
  - mvn org.owasp:dependency-check-maven:check
  - mvn spotbugs:check
